trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'
    includeSymbols: true
    includeSource: true

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishFeedCredentials: 'FeedConnection'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'
    allowPackageConflicts: true
  env:
    FeedConnection: 'https://pkgs.dev.azure.com/mkondrag/301178524_lab4/_packaging/301178524-lab4/nuget/v3/index.json'

